[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.1.4",
    "django-allauth>=65.3.1",
    "django-cors-headers>=4.6.0",
    "djangorestframework>=3.15.2",
]
